package:
  name: ros-noetic-mavros-extras
  version: 1.15.0
source:
  git_url: https://github.com/mavlink/mavros-release.git
  git_rev: release/noetic/mavros_extras/1.15.0-1
  folder: ros-noetic-mavros-extras/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 15
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - setuptools
    - sel(unix): make
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-catkin
    - ros-noetic-cmake-modules
    - ros-noetic-geometry-msgs
    - ros-noetic-mavros
    - ros-noetic-mavros-msgs
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-tf
    - ros-noetic-tf2-eigen
    - ros-noetic-urdf
    - ros-noetic-visualization-msgs
  run:
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-geometry-msgs
    - ros-noetic-mavros
    - ros-noetic-mavros-msgs
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-tf
    - ros-noetic-tf2-eigen
    - ros-noetic-urdf
    - ros-noetic-visualization-msgs
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
