package:
  name: ros-noetic-slam-toolbox
  version: 1.5.7
source:
  git_url: https://github.com/SteveMacenski/slam_toolbox-release.git
  git_rev: release/noetic/slam_toolbox/1.5.7-1
  folder: ros-noetic-slam-toolbox/src/work
  patches:
    - patch/ros-noetic-slam-toolbox.patch

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 15
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - setuptools
    - sel(unix): make
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
    - sel(linux): "{{ cdt('mesa-libgl-devel') }}"
    - sel(linux): "{{ cdt('mesa-dri-drivers') }}"
    - sel(linux): "{{ cdt('libselinux') }}"
    - sel(linux): "{{ cdt('libxdamage') }}"
    - sel(linux): "{{ cdt('libxxf86vm') }}"
    - sel(linux): "{{ cdt('libxfixes') }}"
    - sel(linux): "{{ cdt('libxext') }}"
    - sel(linux): "{{ cdt('libxau') }}"
    - sel(linux): "{{ cdt('libxcb') }}"
  host:
    - ceres-solver
    - eigen
    - gtest
    - liblapack
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - qt-main
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-catkin
    - ros-noetic-cmake-modules
    - ros-noetic-interactive-markers
    - ros-noetic-libg2o
    - ros-noetic-map-server
    - ros-noetic-message-filters
    - ros-noetic-message-runtime
    - ros-noetic-nav-msgs
    - ros-noetic-pluginlib
    - ros-noetic-rosconsole
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
    - ros-noetic-slam-toolbox-msgs
    - ros-noetic-sparse-bundle-adjustment
    - ros-noetic-std-msgs
    - ros-noetic-std-srvs
    - ros-noetic-tf
    - ros-noetic-tf2
    - ros-noetic-tf2-geometry-msgs
    - ros-noetic-tf2-ros
    - ros-noetic-visualization-msgs
    - suitesparse
    - tbb
    - tbb-devel
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
  run:
    - ceres-solver
    - eigen
    - liblapack
    - python
    - qt-main
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-interactive-markers
    - ros-noetic-libg2o
    - ros-noetic-map-server
    - ros-noetic-message-filters
    - ros-noetic-message-runtime
    - ros-noetic-nav-msgs
    - ros-noetic-pluginlib
    - ros-noetic-rosconsole
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
    - ros-noetic-slam-toolbox-msgs
    - ros-noetic-sparse-bundle-adjustment
    - ros-noetic-std-msgs
    - ros-noetic-std-srvs
    - ros-noetic-tf
    - ros-noetic-tf2
    - ros-noetic-tf2-geometry-msgs
    - ros-noetic-tf2-ros
    - ros-noetic-visualization-msgs
    - suitesparse
    - tbb
    - tbb-devel
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
