package:
  name: ros-noetic-franka-ros
  version: 0.10.1
source:
  git_url: https://github.com/frankaemika/franka_ros-release.git
  git_rev: release/noetic/franka_ros/0.10.1-1
  folder: ros-noetic-franka-ros/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 15
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - setuptools
    - sel(unix): make
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-catkin
  run:
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-franka-control
    - ros-noetic-franka-description
    - ros-noetic-franka-example-controllers
    - ros-noetic-franka-gazebo
    - ros-noetic-franka-gripper
    - ros-noetic-franka-hw
    - ros-noetic-franka-msgs
    - ros-noetic-franka-visualization
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
